### PR TITLE
Add lang attr on HTML tag

### PR DESCRIPTION
**Pull request by jasonlemay**

### CODE REVIEW

**Comment by christiangoudreau** [comment]
how is $locale replaced? Did you commit all your changes?

**Comment by jasonlemay** [comment]
I don't know, but it's working :) I took a piece of code that was in the file that I edited. Look at line 8.

**Comment by meriouma** [comment]
It's already a velocity template and the `$locale` variable was already defined ;)

**Comment by christiangoudreau** [comment]
LGTM

**Pull request merged**
