### PR TITLE
aw-159 aw-160 change order main menu & button Products for Expertise 

### PR DESCRIPTION
**Pull request by LarryMatte**
screen shot 2015-05-01 at 10 17 12 am
screen shot 2015-05-01 at 10 17 30 am

### CODE REVIEW

**Comment by christiangoudreau** [comment]
I would even put support bigger, or with a brighter color. @jasonlemay

**Comment by jasonlemay** [comment]
@christiangoudreau agree it could have something more, but subtle ... I'm worried that if we add a brighter color it will look like it's the active page. Maybe a 1px stroke border with padding, like a button?

**Comment by christiangoudreau** [comment]
Yeah, well, as long as it stands out, I agree that if it looks like the active color, it's no good

**Comment by LarryMatte** [comment]
Here's two options,
I tend to go with the first one, it's more subtle/clean and it doesn't look to much of an "active" state.
screen shot 2015-05-01 at 11 16 59 am
screen shot 2015-05-01 at 11 26 23 am

**Comment by christiangoudreau** [comment]
Approved! LGTM

**Comment by LarryMatte** [comment]
ok cool but which one haha ? the one with the border-bottom or the button like ?

**Comment by jasonlemay** [comment]
I'd go with second option (with a bit more of padding-top). Underline is more like the hover state of a link, imo

**Comment by christiangoudreau** [comment]
Oups, second one, I didn't even realize that the first one was different

**Comment by LarryMatte** [comment]
screen shot 2015-05-01 at 12 35 25 pm

**Comment by christiangoudreau** [comment]
LGTM

**Comment by christiangoudreau** [comment]
I would even write: Buy support

**Pull request merged**
