### PR TITLE
Cleaning up some translations

### PR DESCRIPTION
**Pull request by meriouma**
Some keys were duplicated, and the french file didn't have the correct encoding

### CODE REVIEW

**Comment by LarryMatte** [comment]
I think some of those translation (those with SEO in the description and may be more..) still needs to be done by @jasonlemay so I think you shouldn't delete it.

**Comment by meriouma** [comment]
Yeah I know, I only removed the duplicated keys. Those messages are still there. For some unknow reasons, they were present twice

**Comment by christiangoudreau** [comment]
LGTM

**Comment by Pacane** [comment]
LGTM

**Pull request merged**
