### PR TITLE
bees photos

### PR DESCRIPTION
**Pull request by LarryMatte**

### CODE REVIEW

**Comment by Pacane** [comment]
It doesn't want to compile on my side.. Got the same problem @LarryMatte ?

**Comment by LarryMatte** [comment]
@Pacane nop, compile fine on my side

**Comment by jasonlemay** [comment]
LGTM

@LarryMatte t'as pas de close-up?

**Comment by olafleur** [comment]
Et @spg , t'en as pas non plus? Good job les boys, belles photos! ;-)

**Comment by christiangoudreau** [comment]
SP a juste une photo?

**Pull request merged**
